### PR TITLE
MANTA-4341 Optimize conditional object operations

### PR DESCRIPTION
**Pull request by chudley**
This represents the minimum work required to pass conditional parameters to the buckets-mdapi service.

It's not backwards compatible, and while the `conditions` object is optional at buckets-mdapi, it is currently required in node-buckets-mdapi as an argument. This is similar to the `props` argument in some calls, where an empty object is required if these conditions are to be omitted.

I would love to make this `conditions` argument optional here, but I stopped when I realised that doing so is going to start getting messy. It can be done by moving `conditions` to a later position in the arguments and then doing something like:

```
if (!callback && typeof (conditions) === 'function') {
    callback = conditions;
    conditions = {};
    ...
```

... but at this point I think the signature of these methods should just be changed to take an object instead of a list of arguments.  This would make it much easier to check for optional arguments and provide a better interface for backwards compatibility.

I'd be interested to hear if others know of a reason for keeping these calls as an argument list, which I don't have a problem with if we have to. I can understand not doing this in node-moray because there are potentially more consumers, but I'm not sure how many consumers we have of node-buckets-mdapi and whether it's worth biting the bullet now to change the function signature.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
> I'd be interested to hear if others know of a reason for keeping these calls as an argument list, which I don't have a problem with if we have to. I can understand not doing this in node-moray because there are potentially more consumers, but I'm not sure how many consumers we have of node-buckets-mdapi and whether it's worth biting the bullet now to change the function signature.

I don't there's any partciular reason to keep it this way. If you think changing it will work better then that works for me. I think you're right that we don't have that many consumers that will be affected. Basically it's just `buckets-api` and the new gc system that use it, but for the latter case it only uses the two gc-specfiic functions.

**Review by kellymclaughlin — APPROVED** [review]
This looks good to me, but if you decide to rework how the parameters are passed into the functions I'm happy to take another look.

**Comment by chudley** [comment]
Thanks, Kelly! I think I'll just leave it as is. Given that it's pretty much just buckets-api affected by this change I don't think it's much of a bother.

**Comment by chudley** [comment]
Also pushed the v0.7.0 tag: https://github.com/joyent/node-buckets-mdapi/tree/v0.7.0.

**Pull request merged**
